<?php

return [
    'irden' => [
        'code' => 'irden',
        'title' => '09:00 - 12:00',
        'description' => 'Irden eltip berme 09:00 - 12:00. 100 manatdan ýokary söwdada eltip berme mugt',
        'active' => true,
        'start_time' => '09:00',
        'end_time' => '12:00',
        'default_rate' => '20',
        'class' => 'Webkul\Shipping\Carriers\Irden',
    ],
    // 'irden2' => [
    //     'code'             => 'irden2',
    //     'title'            => 'Irden 10:00 - 12:00',
    //     'description'      => 'Irden eltip berme 09:00 - 12:00. 100 manatdan yokary sowdada eltip berme mugt',
    //     'active'           => true,
    //     'start_time'       => '10:00',
    //     'end_time'         => '12:00',
    //     'default_rate'     => '20',
    //     'class'            => 'Webkul\Shipping\Carriers\Irden2',
    // ],
    'obetda' => [
        'code' => 'obetda',
        'title' => '12:00 - 14:00',
        'description' => 'Öýlän eltip berme 12:00 - 14:00 100 manatdan ýokary söwdada eltip berme mugt',
        'active' => true,
        'start_time' => '12:00',
        'end_time' => '14:00',
        'default_rate' => '20',
        'class' => 'Webkul\Shipping\Carriers\Obetda',
    ],
    'ikindi' => [
        'code' => 'ikindi',
        'title' => '14:00 - 16:00',
        'description' => 'Ikindi wagty eltip berme 14:00 - 16:00 100 manatdan ýokary söwdada eltip berme mugt',
        'active' => true,
        'start_time' => '14:00',
        'end_time' => '16:00',
        'default_rate' => '10',
        'class' => 'Webkul\Shipping\Carriers\Ikindi',
    ],
    'agsam' => [
        'code' => 'agsam',
        'title' => '16:00 - 18:00',
        'description' => 'Agşam eltip berme 16:00 - 18:00 100 manatdan ýokary söwdada eltip berme mugt',
        'active' => true,
        'start_time' => '16:00',
        'end_time' => '18:00',
        'default_rate' => '20',
        'class' => 'Webkul\Shipping\Carriers\Agsham',
    ],
    'agsam2' => [
        'code' => 'agsam2',
        'title' => '18:00 - 20:00',
        'description' => 'Agşam eltip berme 18:00 - 20:00 100 manatdan ýokary söwdada eltip berme mugt',
        'active' => true,
        'start_time' => '18:00',
        'end_time' => '20:00',
        'default_rate' => '20',
        'class' => 'Webkul\Shipping\Carriers\Agsham2',
    ],
    'gije' => [
        'code' => 'gije',
        'title' => '20:00 - 22:30',
        'description' => 'Gije eltip berme 20:00 - 22:30 100 manatdan ýokary söwdada eltip berme mugt',
        'active' => true,
        'start_time' => '20:00',
        'end_time' => '22:30',
        'default_rate' => '20',
        'class' => 'Webkul\Shipping\Carriers\Gije',
    ],
    'gije2' => [
        'code' => 'gije2',
        'title' => '22:30 - 00:00',
        'description' => 'Gije eltip berme 22:30 - 00:00 100 manatdan ýokary söwdada eltip berme mugt',
        'active' => true,
        'start_time' => '22:30',
        'end_time' => '00:00',
        'default_rate' => '20',
        'class' => 'Webkul\Shipping\Carriers\Gije2',
    ],

    'free' => [
        'code' => 'free',
        'title' => 'Free Shipping',
        'description' => 'Free Shipping',
        'active' => true,
        'is_calculate_tax' => false,
        'default_rate' => '0',
        'class' => 'Webkul\Shipping\Carriers\Free',
    ],
    'express' => [
        'code' => 'express',
        'title' => 'Express',
        'description' => '1 sagadyn dowamynda eltip berilyar',
        'active' => true,
        'is_calculate_tax' => false,
        'default_rate' => '20',
        'class' => 'Webkul\Shipping\Carriers\Express',
    ],
    'takeaway' => [
        'code' => 'takeaway',
        'title' => 'Özum baryp aljak',
        'description' => '',
        'active' => true,
        'class' => 'Webkul\Shipping\Carriers\Takeaway',
    ],

    'awaza_irden' => [
        'code' => 'awaza_irden',
        'title' => '09:00 - 12:00',
        'description' => 'Irden eltip berme 09:00 - 12:00. 100 manatdan ýokary söwdada eltip berme mugt',
        'active' => true,
        'start_time' => '09:00',
        'end_time' => '12:00',
        'default_rate' => '20',
        'class' => 'Webkul\Shipping\Carriers\Awaza\Irden',
    ],
    // 'irden2' => [
    //     'code'             => 'irden2',
    //     'title'            => 'Irden 10:00 - 12:00',
    //     'description'      => 'Irden eltip berme 09:00 - 12:00. 100 manatdan yokary sowdada eltip berme mugt',
    //     'active'           => true,
    //     'start_time'       => '10:00',
    //     'end_time'         => '12:00',
    //     'default_rate'     => '20',
    //     'class'            => 'Webkul\Shipping\Carriers\Awaza\Irden2',
    // ],
    'awaza_obetda' => [
        'code' => 'awaza_obetda',
        'title' => '12:00 - 14:00',
        'description' => 'Öýlän eltip berme 12:00 - 14:00 100 manatdan ýokary söwdada eltip berme mugt',
        'active' => true,
        'start_time' => '12:00',
        'end_time' => '14:00',
        'default_rate' => '20',
        'class' => 'Webkul\Shipping\Carriers\Awaza\Obetda',
    ],
    'awaza_ikindi' => [
        'code' => 'awaza_ikindi',
        'title' => '14:00 - 16:00',
        'description' => 'Ikindi wagty eltip berme 14:00 - 16:00 100 manatdan ýokary söwdada eltip berme mugt',
        'active' => true,
        'start_time' => '14:00',
        'end_time' => '16:00',
        'default_rate' => '10',
        'class' => 'Webkul\Shipping\Carriers\Awaza\Ikindi',
    ],
    'awaza_agsam' => [
        'code' => 'awaza_agsam',
        'title' => '16:00 - 18:00',
        'description' => 'Agşam eltip berme 16:00 - 18:00 100 manatdan ýokary söwdada eltip berme mugt',
        'active' => true,
        'start_time' => '16:00',
        'end_time' => '18:00',
        'default_rate' => '20',
        'class' => 'Webkul\Shipping\Carriers\Awaza\Agsham',
    ],
    'awaza_agsam2' => [
        'code' => 'awaza_agsam2',
        'title' => '18:00 - 20:00',
        'description' => 'Agşam eltip berme 18:00 - 20:00 100 manatdan ýokary söwdada eltip berme mugt',
        'active' => true,
        'start_time' => '18:00',
        'end_time' => '20:00',
        'default_rate' => '20',
        'class' => 'Webkul\Shipping\Carriers\Awaza\Agsham2',
    ],
    'awaza_gije' => [
        'code' => 'awaza_gije',
        'title' => '20:00 - 22:30',
        'description' => 'Gije eltip berme 20:00 - 22:30 100 manatdan ýokary söwdada eltip berme mugt',
        'active' => true,
        'start_time' => '20:00',
        'end_time' => '22:30',
        'default_rate' => '20',
        'class' => 'Webkul\Shipping\Carriers\Awaza\Gije',
    ],
    'awaza_gije2' => [
        'code' => 'awaza_gije2',
        'title' => '22:30 - 00:00',
        'description' => 'Gije eltip berme 22:30 - 00:00 100 manatdan ýokary söwdada eltip berme mugt',
        'active' => true,
        'start_time' => '22:30',
        'end_time' => '00:00',
        'default_rate' => '20',
        'class' => 'Webkul\Shipping\Carriers\Awaza\Gije2',
    ],

    'awaza_free' => [
        'code' => 'awaza_free',
        'title' => 'Free Shipping',
        'description' => 'Free Shipping',
        'active' => true,
        'is_calculate_tax' => false,
        'default_rate' => '0',
        'class' => 'Webkul\Shipping\Carriers\Awaza\Free',
    ],
    'awaza_express' => [
        'code' => 'awaza_express',
        'title' => 'Express',
        'description' => '1 sagadyn dowamynda eltip berilyar',
        'active' => true,
        'is_calculate_tax' => false,
        'default_rate' => '20',
        'class' => 'Webkul\Shipping\Carriers\Awaza\Express',
    ],
    'awaza_takeaway' => [
        'code' => 'awaza_takeaway',
        'title' => 'Özum baryp aljak(Awaza)',
        'description' => '',
        'active' => true,
        'class' => 'Webkul\Shipping\Carriers\Awaza\Takeaway',
    ],

];
