<?php

return [
    [
        'key' => 'sales',
        'name' => 'admin::app.admin.system.sales',
        'sort' => 5,
    ],
    [
        'key' => 'sales.carriers',
        'name' => 'admin::app.admin.system.shipping-methods',
        'sort' => 1,
    ],
    [
        'key' => 'sales.carriers.free',
        'name' => 'admin::app.admin.system.free-shipping',
        'sort' => 1,
        'fields' => [
            [
                'name' => 'title',
                'title' => 'admin::app.admin.system.title',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => true,
            ],
            [
                'name' => 'description',
                'title' => 'admin::app.admin.system.description',
                'type' => 'textarea',
                'channel_based' => false,
                'locale_based' => true,
            ],
            [
                'name' => 'active',
                'title' => 'admin::app.admin.system.status',
                'type' => 'boolean',
                'validation' => 'required',
                'channel_based' => false,
                'locale_based' => true,
            ],
            [
                'name' => 'is_calculate_tax',
                'title' => 'admin::app.admin.system.calculate-tax',
                'type' => 'boolean',
                'validation' => 'required',
                'channel_based' => false,
                'locale_based' => false,
            ],
        ],
    ],
    [
        'key' => 'sales.carriers.irden',
        'name' => 'Irden dostawka',
        'sort' => 3,
        'fields' => [
            [
                'name' => 'title',
                'title' => 'admin::app.admin.system.title',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => true,
            ],
            [
                'name' => 'description',
                'title' => 'admin::app.admin.system.description',
                'type' => 'textarea',
                'channel_based' => false,
                'locale_based' => true,
            ],
            [
                'name' => 'default_rate',
                'title' => 'admin::app.admin.system.rate',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'start_time',
                'title' => 'Başlaýan wagty',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'end_time',
                'title' => 'Gutarýan wagty',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'active',
                'title' => 'admin::app.admin.system.status',
                'type' => 'boolean',
                'validation' => 'required',
                'channel_based' => false,
                'locale_based' => false,
            ],
        ],
    ],
    [
        'key' => 'sales.carriers.obetda',
        'name' => 'Obetda dostawka',
        'sort' => 3,
        'fields' => [
            [
                'name' => 'title',
                'title' => 'admin::app.admin.system.title',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => true,
            ],
            [
                'name' => 'description',
                'title' => 'admin::app.admin.system.description',
                'type' => 'textarea',
                'channel_based' => false,
                'locale_based' => true,
            ],
            [
                'name' => 'default_rate',
                'title' => 'admin::app.admin.system.rate',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'start_time',
                'title' => 'Başlaýan wagty',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'end_time',
                'title' => 'Gutarýan wagty',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'active',
                'title' => 'admin::app.admin.system.status',
                'type' => 'boolean',
                'validation' => 'required',
                'channel_based' => false,
                'locale_based' => false,
            ],
        ],
    ],
    [
        'key' => 'sales.carriers.ikindi',
        'name' => 'Ikindi dostawka',
        'sort' => 3,
        'fields' => [
            [
                'name' => 'title',
                'title' => 'admin::app.admin.system.title',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => true,
            ],
            [
                'name' => 'description',
                'title' => 'admin::app.admin.system.description',
                'type' => 'textarea',
                'channel_based' => false,
                'locale_based' => true,
            ],
            [
                'name' => 'default_rate',
                'title' => 'admin::app.admin.system.rate',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'start_time',
                'title' => 'Başlaýan wagty',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'end_time',
                'title' => 'Gutarýan wagty',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'active',
                'title' => 'admin::app.admin.system.status',
                'type' => 'boolean',
                'validation' => 'required',
                'channel_based' => false,
                'locale_based' => false,
            ],
        ],
    ],
    [
        'key' => 'sales.carriers.agsam',
        'name' => 'Agşam dostawka',
        'sort' => 4,
        'fields' => [
            [
                'name' => 'title',
                'title' => 'admin::app.admin.system.title',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => true,
            ],
            [
                'name' => 'description',
                'title' => 'admin::app.admin.system.description',
                'type' => 'textarea',
                'channel_based' => false,
                'locale_based' => true,
            ],
            [
                'name' => 'default_rate',
                'title' => 'admin::app.admin.system.rate',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'start_time',
                'title' => 'Başlaýan wagty',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'end_time',
                'title' => 'Gutarýan wagty',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'active',
                'title' => 'admin::app.admin.system.status',
                'type' => 'boolean',
                'validation' => 'required',
                'channel_based' => false,
                'locale_based' => false,
            ],
        ],
    ],
    [
        'key' => 'sales.carriers.agsam2',
        'name' => 'Agşam 2-nji dostawka',
        'sort' => 4,
        'fields' => [
            [
                'name' => 'title',
                'title' => 'admin::app.admin.system.title',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => true,
            ],
            [
                'name' => 'description',
                'title' => 'admin::app.admin.system.description',
                'type' => 'textarea',
                'channel_based' => false,
                'locale_based' => true,
            ],
            [
                'name' => 'default_rate',
                'title' => 'admin::app.admin.system.rate',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'start_time',
                'title' => 'Başlaýan wagty',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'end_time',
                'title' => 'Gutarýan wagty',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'active',
                'title' => 'admin::app.admin.system.status',
                'type' => 'boolean',
                'validation' => 'required',
                'channel_based' => false,
                'locale_based' => false,
            ],
        ],
    ],
    [
        'key' => 'sales.carriers.gije',
        'name' => 'Gije dostawka',
        'sort' => 5,
        'fields' => [
            [
                'name' => 'title',
                'title' => 'admin::app.admin.system.title',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => true,
            ],
            [
                'name' => 'description',
                'title' => 'admin::app.admin.system.description',
                'type' => 'textarea',
                'channel_based' => false,
                'locale_based' => true,
            ],
            [
                'name' => 'default_rate',
                'title' => 'admin::app.admin.system.rate',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'start_time',
                'title' => 'Başlaýan wagty',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'end_time',
                'title' => 'Gutarýan wagty',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'active',
                'title' => 'admin::app.admin.system.status',
                'type' => 'boolean',
                'validation' => 'required',
                'channel_based' => false,
                'locale_based' => false,
            ],
        ],
    ],

    [
        'key' => 'sales.carriers.gije2',
        'name' => 'Gije 2nji dostawka',
        'sort' => 5,
        'fields' => [
            [
                'name' => 'title',
                'title' => 'admin::app.admin.system.title',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => true,
            ],
            [
                'name' => 'description',
                'title' => 'admin::app.admin.system.description',
                'type' => 'textarea',
                'channel_based' => false,
                'locale_based' => true,
            ],
            [
                'name' => 'default_rate',
                'title' => 'admin::app.admin.system.rate',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'start_time',
                'title' => 'Başlaýan wagty',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'end_time',
                'title' => 'Gutarýan wagty',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'active',
                'title' => 'admin::app.admin.system.status',
                'type' => 'boolean',
                'validation' => 'required',
                'channel_based' => false,
                'locale_based' => false,
            ],
        ],
    ],

    [
        'key' => 'sales.carriers.express',
        'name' => 'Express shipping',
        'sort' => 6,
        'fields' => [
            [
                'name' => 'title',
                'title' => 'admin::app.admin.system.title',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => true,
            ],
            [
                'name' => 'description',
                'title' => 'admin::app.admin.system.description',
                'type' => 'textarea',
                'channel_based' => false,
                'locale_based' => true,
            ],
            [
                'name' => 'default_rate',
                'title' => 'admin::app.admin.system.rate',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'active',
                'title' => 'admin::app.admin.system.status',
                'type' => 'boolean',
                'validation' => 'required',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'is_calculate_tax',
                'title' => 'admin::app.admin.system.calculate-tax',
                'type' => 'boolean',
                'validation' => 'required',
                'channel_based' => false,
                'locale_based' => false,
            ],
        ],
    ],
    [
        'key' => 'sales.carriers.takeaway',
        'name' => 'Özüm baryp aljak',
        'sort' => 7,
        'fields' => [
            [
                'name' => 'title',
                'title' => 'admin::app.admin.system.title',
                'type' => 'depends',
                'depend' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => false,
                'locale_based' => true,
            ],
            [
                'name' => 'description',
                'title' => 'admin::app.admin.system.description',
                'type' => 'textarea',
                'channel_based' => false,
                'locale_based' => true,
            ],
            [
                'name' => 'active',
                'title' => 'admin::app.admin.system.status',
                'type' => 'boolean',
                'validation' => 'required',
                'channel_based' => false,
                'locale_based' => false,
            ],
        ],
    ],
    [
        'key' => 'sales.shipping',
        'name' => 'admin::app.admin.system.shipping',
        'sort' => 0,
    ],
    [
        'key' => 'sales.shipping.origin',
        'name' => 'admin::app.admin.system.origin',
        'sort' => 0,
        'fields' => [
            [
                'name' => 'country',
                'title' => 'admin::app.admin.system.country',
                'type' => 'country',
                'validation' => 'required',
                'channel_based' => true,
                'locale_based' => true,
            ],
            [
                'name' => 'state',
                'title' => 'admin::app.admin.system.state',
                'type' => 'state',
                'validation' => 'required',
                'channel_based' => true,
                'locale_based' => true,
            ],
            [
                'name' => 'city',
                'title' => 'admin::app.admin.system.city',
                'type' => 'text',
                'validation' => 'required',
                'channel_based' => true,
                'locale_based' => false,
            ],
            [
                'name' => 'address1',
                'title' => 'admin::app.admin.system.street-address',
                'type' => 'text',
                'validation' => 'required',
                'channel_based' => true,
                'locale_based' => false,
            ],
            [
                'name' => 'zipcode',
                'title' => 'admin::app.admin.system.zip',
                'type' => 'text',
                'validation' => 'required',
                'channel_based' => true,
                'locale_based' => false,
            ],
            [
                'name' => 'store_name',
                'title' => 'admin::app.admin.system.store-name',
                'type' => 'text',
                'channel_based' => true,
            ],
            [
                'name' => 'vat_number',
                'title' => 'admin::app.admin.system.vat-number',
                'type' => 'text',
                'channel_based' => true,
            ],
            [
                'name' => 'contact',
                'title' => 'admin::app.admin.system.contact-number',
                'type' => 'text',
                'channel_based' => true,
            ],
            [
                'name' => 'bank_details',
                'title' => 'admin::app.admin.system.bank-details',
                'type' => 'textarea',
                'channel_based' => true,
            ],
        ],
    ],
];
